# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60f52fd39ca7c30b13b9ab80251e3550740e2a9f1e648255105e80248c97a81746992429ec15a2da6a6e13dbbbc1f6b0332f771fcc03aa098cdd65404c2bc0e0

test:
  secret_key_base: 0f895339d16423a9fc9738598ef374a82d56ffa836b5e784b421c0b645749703a57e9a38117a7fc710adcfeffd49f512d16bdac8e4d6c2d5bcba2e688ab015ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
